# Generated by Django 6.0.5 on 2026-05-28 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_code', models.CharField(choices=[('MISSING_MANDATORY_FIELD', 'Missing Mandatory Field'), ('DUPLICATE_ROW', 'Duplicate Row'), ('INVALID_DATE', 'Invalid Date'), ('NEGATIVE_QUANTITY', 'Negative Quantity'), ('IMPOSSIBLE_QUANTITY', 'Statistically Impossible Quantity'), ('UNIT_UNRECOGNIZED', 'Unrecognized Unit'), ('MISSING_OPTIONAL_FIELD', 'Missing Optional Field'), ('DATE_OUTSIDE_PERIOD', 'Date Outside Expected Period')], max_length=30)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=10)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingestion_validationflag',
            },
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('source_type', models.CharField(max_length=30)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALID', 'Valid'), ('FLAGGED', 'Flagged'), ('FAILED', 'Failed')], default='PENDING', max_length=25)),
                ('checksum', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'ingestion_rawrow',
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('CORPORATE_TRAVEL', 'Corporate Travel')], max_length=30)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'ingestion_uploadbatch',
            },
        ),
    ]
