# Generated by Django 6.0.5 on 2026-05-28 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='validationflag',
            name='raw_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='ingestion.rawrow'),
        ),
        migrations.AddField(
            model_name='validationflag',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_u_tenant__5f4d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['tenant', 'source_type'], name='ingestion_u_tenant__e79910_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['file_hash'], name='ingestion_u_file_ha_dfed61_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrow',
            index=models.Index(fields=['tenant', 'batch'], name='ingestion_r_tenant__c60e17_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrow',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_r_tenant__00a106_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrow',
            index=models.Index(fields=['checksum'], name='ingestion_r_checksu_ff243c_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrow',
            index=models.Index(fields=['tenant', 'source_type', 'status'], name='ingestion_r_tenant__da411c_idx'),
        ),
        migrations.AddIndex(
            model_name='validationflag',
            index=models.Index(fields=['raw_row'], name='ingestion_v_raw_row_893c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='validationflag',
            index=models.Index(fields=['tenant', 'flag_code'], name='ingestion_v_tenant__584cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='validationflag',
            index=models.Index(fields=['tenant', 'severity'], name='ingestion_v_tenant__bae2da_idx'),
        ),
    ]
