# Generated by Django 6.0.5 on 2026-05-28 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0002_initial'),
        ('reviews', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdecision',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='emission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='emissions.normalizedemission'),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='reviewdecision',
            index=models.Index(fields=['tenant', 'status'], name='reviews_rev_tenant__b43978_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdecision',
            index=models.Index(fields=['tenant', 'analyst'], name='reviews_rev_tenant__fed876_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdecision',
            index=models.Index(fields=['tenant', 'is_locked'], name='reviews_rev_tenant__5d4148_idx'),
        ),
    ]
