# Generated by Django 6.0.5 on 2026-05-28 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.SmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_type', models.CharField(max_length=60)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity_raw', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_raw', models.CharField(max_length=30)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_normalized', models.CharField(max_length=30)),
                ('kg_co2e', models.DecimalField(decimal_places=6, max_digits=15)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('source_label', models.CharField(max_length=200)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emissions_normalizedemission',
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('DIESEL_COMBUSTION', 'Diesel Combustion'), ('PETROL_COMBUSTION', 'Petrol Combustion'), ('NATURAL_GAS_COMBUSTION', 'Natural Gas Combustion'), ('HEATING_OIL_COMBUSTION', 'Heating Oil Combustion'), ('LPG_COMBUSTION', 'LPG Combustion'), ('BIODIESEL_COMBUSTION', 'Biodiesel Combustion'), ('FURNACE_OIL_COMBUSTION', 'Furnace Oil Combustion'), ('GRID_ELECTRICITY_UK', 'UK Grid Electricity'), ('GRID_ELECTRICITY_DE', 'German Grid Electricity'), ('GRID_ELECTRICITY_IN', 'Indian Grid Electricity'), ('GRID_ELECTRICITY_EU', 'EU Grid Electricity'), ('GRID_ELECTRICITY_UNKNOWN', 'Unknown Grid Electricity'), ('FLIGHT_DOMESTIC', 'Flight Domestic'), ('FLIGHT_SHORT_HAUL', 'Flight Short Haul'), ('FLIGHT_LONG_HAUL', 'Flight Long Haul'), ('HOTEL_STAY', 'Hotel Stay'), ('GROUND_TRANSPORT_TAXI', 'Ground Transport Taxi'), ('GROUND_TRANSPORT_RENTAL', 'Ground Transport Car Rental'), ('GROUND_TRANSPORT_RAIL', 'Ground Transport Rail')], max_length=60)),
                ('scope', models.SmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('unit', models.CharField(max_length=30)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=8, max_digits=12)),
                ('source_reference', models.CharField(max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'emissions_emissionfactor',
                'indexes': [models.Index(fields=['activity_type', 'is_active'], name='emissions_e_activit_99a72f_idx')],
                'unique_together': {('activity_type', 'unit', 'valid_from')},
            },
        ),
    ]
