# Generated by Django 6.0.5 on 2026-05-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedemission',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='emission_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor'),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='raw_row',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emission', to='ingestion.rawrow'),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='normalizedemission',
            index=models.Index(fields=['tenant', 'scope'], name='emissions_n_tenant__d67e33_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemission',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='emissions_n_tenant__05fdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemission',
            index=models.Index(fields=['tenant', 'activity_type'], name='emissions_n_tenant__d46d97_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemission',
            index=models.Index(fields=['tenant', 'batch'], name='emissions_n_tenant__a3c1a4_idx'),
        ),
    ]
