# Generated by Django 6.0.5 on 2026-05-28 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('BATCH_INGESTED', 'Batch Ingested'), ('ROW_VALIDATED', 'Row Validated'), ('ROW_FLAGGED', 'Row Flagged'), ('ROW_NORMALIZED', 'Row Normalized'), ('ROW_APPROVED', 'Row Approved'), ('ROW_REJECTED', 'Row Rejected'), ('NOTE_EDITED', 'Analyst Note Edited'), ('ROW_UNLOCKED', 'Row Unlocked by Admin')], max_length=40)),
                ('object_id', models.UUIDField()),
                ('object_repr', models.CharField(max_length=300)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_auditlog',
            },
        ),
    ]
